module.exports = {
  Ping: require('./ping'),
  GPU: require('./alternate-gpu-tracker'),
  Giphy: require('./giphy'),
  Help: require('./commandsList'),
  Steam: require('./steam'),
  Dosh: require('./dosh'),
  Wiki: require('./wiki'),
  Translator: require('./translator'),
  UnitConverter: require('./convertUnits'),
  Jokes: require('./jokes'),
  Lyrics: require('./lyrics'),
  WordFind: require('./wordFind'),
  Watch2Gether: require('./watch2gether'),
};
