# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        touch .env
        echo DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} >> .env
        echo GIPHY_KEY=${{ secrets.GIPHY_KEY }} >> .env
        echo GOOGLE_KEYFILENAME=${{ secrets.GOOGLE_KEYFILENAME }} >> .env
        echo GOOGLE_PROJECT_ID=${{ secrets.GOOGLE_PROJECT_ID }} >> .env
        echo STEAM_KEY=${{ secrets.STEAM_KEY }} >> .env
        echo WATCH2GETHER_KEY=${{ secrets.WATCH2GETHER_KEY}} >> .env
    - run: |
        touch ${{secrets.GOOGLEKEYFILENAME}}
        echo ${{secrets.GCLOUD_KEY}} >> ${{secrets.GOOGLEKEYFILENAME}}
    - run: npm i
    - run: pm2 restart ziggato
